[package]
name = "drygon"
version = "0.1.0"
edition = "2021"

[dependencies]
raylib = { version = "3.7" }
drython = { git = "https://github.com/NocturnalWisp/Drython-Parser.git" }
yaml-rust = "0.4"
downcast-rs = "1.2.0"
